[package]
name = "vulkeng"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
ctrlc = "3.4"
log = "0.4"
pretty_env_logger = "0.5"
thiserror = "2.0"
winit = { version = "0.30", default-features = false, features = ["wayland"] }

[build-dependencies]
pkg-config = "0.3"
